Fix glitchy level selection after command line level load
SuperV1234/SSVOpenHexagon pull request #317
Opened 2021-01-10 20:33 UTC by IvoryDuke

As per title.
A small fix to address wonky behavior in the level selection menu after using the command line level load.

2021-01-10 21:22 UTC, InfoTeddy requested changes

2021-01-10 21:22 UTC, InfoTeddy commented on src/SSVOpenHexagon/Core/MenuGame.cpp
> +	changeStateTo(States::LevelSelection);
This code is indented with tabs instead of 4 spaces like the surrounding code.

2021-01-10 23:15 UTC, InfoTeddy approved these changes

2021-01-23 11:58 UTC, SuperV1234 approved these changes
lgtm

2021-01-23 11:58 UTC, merged